exception_thrown: '"AttributeError: ''NoneType'' object has no attribute ''test''"'
options:
  config_file: config.yml
  default_dirs: []
  error_file: stderr.txt
  exist_ok: true
  git_hash: c0ac22e
  output_dir: example/student1/
  output_file: stdout.txt
  timestamp: 2020-10-22-12:16:42
  verbose: true
tutorial: []
verbose: false
